---
# LILYGO-T-Higrow-ESP32 Plant sensor

##################################################
# Substitutions variables
##################################################
substitutions:
  # Dashes are not supported in devicename
  devicename: "lilygo"
  device_description: "LILYGO Plant Sensor"
  project_version: "1.1.0"
  update_interval: 1min
  loglevel: DEBUG
  moisture_min: "2.83"
  moisture_max: "1.37"
  conductivity_min: "0.075"
  conductivity_max: "0.34"
  # Uncomment run_duration and sleep_duration if you want to use deepsleep
  # set how long to stay awake - NOT less then 10sec
  # run_duration: 11s
  # set how long to sleep in minutes
  # sleep_duration: 60min

###################################################
# Board Configuration
###################################################
esphome:
  name: "${devicename}"
  comment: "${device_description}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: esphome.soil-sensor
    version: "${project_version}"
  on_boot:
    priority: 240
    then:
      - wait_until:
          condition:
            wifi.connected:
          timeout: 10s
  on_shutdown:
    then:
      - switch.turn_off: spower

dashboard_import:
  package_import_url: github://Shubhranshu2411/LILYGO-T-Higrow-Esphome/LILYGO-T-Higrow-ESP32.yaml@main
  import_full_config: true
esp32:
  board: esp32dev
  framework:
    type: arduino

improv_serial:

wifi:
  # Use improv (after installing either go to web.esphome.io or use the installer here: https://bruvv.github.io/LILYGO-T-Higrow-Esphome)
  # ssid: !secret wifi_ssid
  # password: !secret wifi_password
  # fast_connect: True

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename}"

captive_portal:

# Web server disabled because it was using to much ram
web_server:
# port: 80

# Enable logging
logger:
  level: "${loglevel}"
# Enable Home Assistant API
api:
# Allow Over-The-Air updates
ota:
  - platform: esphome
    id: ota_esphome

  - platform: http_request
    id: ota_http_request

# ota:
#   enabled: ${ota_enabled}
#   url: https://github.com/your-username/your-repo-name/raw/main/firmware/${device_name}.bin
#   username: !secret ota_username
#   password: !secret ota_password


update:
  - platform: http_request
    id: update_http_request
    name: Firmware
    source: https://github.com/Shubhranshu2411/LILYGO-T-Higrow-Esphome/lilygo-esp32/manifest.json

http_request:

esp32_improv:
  authorizer: none

time:
  - platform: homeassistant

button:
  - platform: restart
    name: "Restart - ${devicename}"

i2c:
  sda: 25
  scl: 26
  scan: true
  id: bus_a
  setup_priority: -200

switch:
  # Power Switch
  - platform: gpio
    name: "${devicename} Sensor Power switch"
    pin:
      number: 4
      mode: INPUT_PULLUP
    id: spower
    restore_mode: ALWAYS_ON
    internal: true
    setup_priority: 1000
  - platform: template
    name: "Auto Update"
    id: auto_update_switch
    turn_on_action:
      - lambda: id(ota_github).auto_update = true;
    turn_off_action:
      - lambda: id(ota_github).auto_update = false;

sensor:
  # Wifi sensor
  - platform: wifi_signal
    name: "${devicename} WiFi Signal"
    id: "${devicename}_wifi_signal"
    update_interval: ${update_interval}

packages:
  text_sensors: !include common/text_sensors.yaml
  dht: !include common/dht.yaml
  plantsensors: !include common/plantsensors.yaml
  # waterpump: !include common/waterpump.yaml
  # bluetooth: !include common/bluetooth.yaml
  # Battery only works for 12 hours with deepsleep!
  # bme280: !include common/bme280.yaml
  # deepsleep: !include common/deepsleep.yaml
  # battery: !include common/battery.yaml
