---
name: Build and publish firmware

on:
  workflow_dispatch:
    inputs:                         # Comment if automatic ESPHOME version is enabled
      esphome_version:
        description: 'ESPHome version'
        required: true
        default: '2024.7.1'
      # publish_type:
      #   description: 'Publish Type (Test/Release)'
      #   required: true
      #   default: 'test'

jobs:
  build:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - LILYGO-T-Higrow-ESP32.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.7
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .github/yamllint.yml
      # - name: Get latest ESPHome version
      #   uses: actions/cache@v3
      #   with:
      #       path: ~/.esphomerc
      #       key: esphome-versions-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
      # - run: |
      #     echo "latest_version=$(esphome --version | cut -d' ' -f3)" >> $HOME/.esphomerc
      - name: Build ESPHome firmware to verify configuration
        uses: esphome/build-action@v3.2.0
        id: esphome-build
        with:
          yaml_file: ${{ matrix.file }}
          version: ${{ inputs.esphome_version }}
          # version: ${{ cat $HOME/.esphomerc | grep latest_version | cut -d'=' -f2 }}

      - run: |
          mkdir output
          mv "${{ steps.esphome-build.outputs.name }}" output/

      - uses: actions/upload-artifact@v4.3.3
        with:
          name: firmware
          path: output

  publish-test:
    needs: build
    name: Publish test firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/download-artifact@v4.1.7
        with:
          path: output
          name: firmware

      - run: |
          mkdir output-test
          cp -r output/* output-test/

      - uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: gh-pages-test
          folder: output-test
          clean: true

  release:
    needs: build
    name: Release firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/download-artifact@v4.1.7
        with:
          path: output
          name: firmware

      - run: |
          mkdir output-release
          cp -r output/* output-release/

      - uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: gh-pages-release
          folder: output-release
          clean: true

      - name: Create GitHub Release
        uses: actions/create-release@v1.1.4
        # env:
        #   github_token: ${{ secrets.MY_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Firmware Release ${{ github.sha }}
          body: |
            New firmware release!
          token: ${{ secrets.MY_TOKEN }}